version: '3'

services:
  api:
    depends_on:
      - mongodb
      - mysql
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - 8080:8080
    env_file:
      - .env
      - .env.secure
  mongodb:
    build: ./database/mongodb
    ports:
      - 27017:27017
    volumes:
      -  ./db-data/mongodb:/data/db
    env_file:
      - .env
      - .env.secure
  mysql:
    build: ./database/mysql
    ports:
      - 3306:3306
    volumes:
      - ./db-data/mysql:/var/lib/mysql
    env_file:
      - .env
      - .env.secure
